import { invokeLLM } from "./_core/llm";
import * as db from "./db";
import { fetchAllJSEStocks, getMarketOverview } from "./marketData";

export interface NewsletterContent {
  subject: string;
  htmlContent: string;
  textContent: string;
  generatedAt: Date;
}

/**
 * Generate weekly newsletter content using AI
 */
export async function generateWeeklyNewsletter(): Promise<NewsletterContent> {
  // Fetch current market data
  const stocks = await fetchAllJSEStocks();
  const marketData = await getMarketOverview();

  // Prepare market summary for AI
  const marketSummary = `
Current JSE Market Status:
- ECM Confidence: ${marketData.ecm.confidence}%
- Market Direction: ${marketData.ecm.direction}
- Cycle Position: ${marketData.ecm.cyclePosition}
- Support Index: ${marketData.ecm.supportLevel} pts
- Resistance Index: ${marketData.ecm.resistanceLevel} pts

Top Performing Stocks:
${stocks
  .sort((a: any, b: any) => b.priceChangePercent - a.priceChangePercent)
  .slice(0, 5)
  .map(
    (s: any) =>
      `- ${s.symbol}: R${s.currentPrice.toFixed(2)} (${s.priceChangePercent >= 0 ? "+" : ""}${s.priceChangePercent.toFixed(2)}%)`
  )
  .join("\n")}

Worst Performing Stocks:
${stocks
  .sort((a: any, b: any) => a.priceChangePercent - b.priceChangePercent)
  .slice(0, 5)
  .map(
    (s: any) =>
      `- ${s.symbol}: R${s.currentPrice.toFixed(2)} (${s.priceChangePercent >= 0 ? "+" : ""}${s.priceChangePercent.toFixed(2)}%)`
  )
  .join("\n")}

Sector Performance:
${marketData.sectors
  .map((s: any) => `- ${s.sector}: ${s.performance >= 0 ? "+" : ""}${s.performance.toFixed(2)}%`)
  .join("\n")}
`;

  // Generate newsletter content using AI
  const response = await invokeLLM({
    messages: [
      {
        role: "system",
        content: `You are a professional financial analyst writing a weekly market newsletter for South African traders. 
Your newsletter should be:
- Professional but accessible
- Data-driven with specific numbers
- Actionable with clear insights
- Formatted in clean HTML
- Include sections: Market Overview, Top Movers, Sector Analysis, ECM Insights, Week Ahead Outlook

Use the Economic Confidence Model (ECM) methodology by Martin Armstrong to provide cycle-based predictions.`,
      },
      {
        role: "user",
        content: `Generate a comprehensive weekly market newsletter based on this data:\n\n${marketSummary}`,
      },
    ],
  });

  const aiContent = typeof response.choices[0].message.content === 'string' 
    ? response.choices[0].message.content 
    : JSON.stringify(response.choices[0].message.content);

  // Generate subject line
  const subjectResponse = await invokeLLM({
    messages: [
      {
        role: "system",
        content:
          "Generate a compelling email subject line for a weekly JSE market newsletter. Keep it under 60 characters, professional, and attention-grabbing.",
      },
      {
        role: "user",
        content: `Based on this market data, create a subject line:\nECM Confidence: ${marketData.ecm.confidence}%\nDirection: ${marketData.ecm.direction}\nTop gainer: ${stocks.sort((a: any, b: any) => b.priceChangePercent - a.priceChangePercent)[0].symbol} +${stocks.sort((a: any, b: any) => b.priceChangePercent - a.priceChangePercent)[0].priceChangePercent.toFixed(2)}%`,
      },
    ],
  });

  const subjectContent = typeof subjectResponse.choices[0].message.content === 'string'
    ? subjectResponse.choices[0].message.content
    : JSON.stringify(subjectResponse.choices[0].message.content);
  const subject = subjectContent.replace(/['"]/g, "").trim();

  // Convert to HTML if not already
  const htmlContent = aiContent.includes("<html>")
    ? aiContent
    : `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #7c3aed; margin-top: 30px; }
    .metric { background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 10px 0; }
    .positive { color: #10b981; font-weight: bold; }
    .negative { color: #ef4444; font-weight: bold; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; }
  </style>
</head>
<body>
  <h1>Siener AI Weekly Market Report</h1>
  ${aiContent}
  <div class="footer">
    <p>This newsletter was generated by Siener AI using the Economic Confidence Model (ECM) methodology.</p>
    <p>© ${new Date().getFullYear()} Siener AI. All rights reserved.</p>
  </div>
</body>
</html>
`;

  // Strip HTML for text version
  const textContent = aiContent
    .replace(/<[^>]*>/g, "")
    .replace(/\n\n+/g, "\n\n")
    .trim();

  return {
    subject,
    htmlContent,
    textContent,
    generatedAt: new Date(),
  };
}

/**
 * Send newsletter to all active subscribers
 */
export async function sendWeeklyNewsletter(): Promise<{
  sent: number;
  failed: number;
}> {
  // Generate newsletter content
  const newsletter = await generateWeeklyNewsletter();

  // Get all active subscribers
  const subscribers = await db.getActiveSubscribers();

  let sent = 0;
  let failed = 0;

  // Send to each subscriber
  for (const subscriber of subscribers) {
    try {
      // TODO: Integrate with email service (SendGrid, AWS SES, etc.)
      // For now, just save to database
      await db.saveNewsletterRecord({
        userId: subscriber.id,
        subject: newsletter.subject,
        content: newsletter.htmlContent,
        sentAt: new Date(),
      });
      sent++;
    } catch (error) {
      console.error(`Failed to send newsletter to user ${subscriber.id}:`, error);
      failed++;
    }
  }

  return { sent, failed };
}

/**
 * Get newsletter archive for a user
 */
export async function getUserNewsletters(userId: number) {
  return await db.getUserNewsletters(userId);
}
